### ISSUE TITLE
question or feature request

### ISSUE THREAD

**Issue by netfun81** [serprex/nobox#1]
I like your window manager it does everything I need.   The only thing is i want to change from using the ALT key to using the WIN key for all functions (including move/resize).   When i change the keycode from 64 to 133, i can get the WIN key to launch my programs however it will not move and resize windows.   I changed the XCB_MOD_MASK_1 to XCB_MOD_MASK_4 but still didn't work.   I guess i don't understand how you are grabbing the WIN key in the code.   I can make it all work using the CONTROL key however I prefer to use the WIN key as it leaves the CNTRL and ALT available to other programs.   

Can you explain how you are grabbing the WIN key in your code?  and how I might disable the maximize/delete behavior and use it fully in place of the ALT key?

**Comment by serprex** [comment]
Move xcb_grab_button out of the loop & only grab WIN modifier

If you don't care for fullscreen/close click behavior, update

```
case 1:goto*(my==XCB_MOD_MASK_1?&&mvsz:&&full);
case 3:goto*(my==XCB_MOD_MASK_1?&&mvsz:&&shut);
```

to

```
case 1:case 3:goto mvsz;
```

**Comment by netfun81** [comment]
Thanks for the reply!   I tried as you suggested but the move/resize function did not work. 

How is the best way to only grab the WIN modifier?

**Comment by serprex** [comment]
xcb_grab_button(d,1,rt,XCB_EVENT_MASK_BUTTON_PRESS,XCB_GRAB_MODE_ASYNC,XCB_GRAB_MODE_ASYNC,XCB_NONE,XCB_NONE,XCB_GRAB_ANY,XCB_MOD_MASK_4);

**Comment by netfun81** [comment]
Thanks! that worked.  And thanks for the great minimal window manager!
